name: flutter_landing_page
description: "유니콘 : 제 1회 수도권 대학 연합 IT 컨퍼런스"
publish_to: "none"
version: 1.4.1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  card_swiper: ^3.0.1
  dart_fusion:
    git:
      url: https://github.com/Nialixus/dart_fusion.git
      ref: v2.9.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  go_router: ^13.0.1
  http: ^1.1.0
  meta_seo: ^3.0.7
  scroll_to_id: ^1.5.1
  seo: ^0.0.5
  url_launcher: ^6.2.1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  package_rename: ^1.5.1

flutter:
  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Black.otf
        - asset: assets/fonts/Pretendard-Bold.otf
        - asset: assets/fonts/Pretendard-ExtraBold.otf
        - asset: assets/fonts/Pretendard-ExtraLight.otf
        - asset: assets/fonts/Pretendard-Light.otf
        - asset: assets/fonts/Pretendard-Medium.otf
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-SemiBold.otf
        - asset: assets/fonts/Pretendard-Thin.otf

  assets:
    - assets/image/school-logos/
    - assets/image/
